<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Authors>luttje</Authors>
    <Title>Key2Joy</Title>
    <Product>Key2Joy</Product>
    <Description>Simulate a game controller with your mouse and keyboard</Description>
    <Copyright>Copyright © 2026 luttje</Copyright>
    <PackageProjectUrl>https://github.com/luttje/Key2Joy</PackageProjectUrl>
    <VersionPrefix>0.8.0</VersionPrefix>
    <TargetFramework>net9.0-windows</TargetFramework>
    <LangVersion>latest</LangVersion>
    <RootNamespace>Key2Joy.Contracts</RootNamespace>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <SignAssembly>False</SignAssembly>
    <AssemblyOriginatorKeyFile />
    <BaseOutputPath>bin\$(MSBuildProjectName)</BaseOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Text.Json" Version="9.0.14" />
  </ItemGroup>

</Project>
