using System;
using System.Collections.ObjectModel;
using CommunityToolkit.Mvvm.ComponentModel;
using Key2Joy.Contracts.Mapping;
using Key2Joy.Contracts.Mapping.Actions;
using Key2Joy.Mapping.Actions.Logic;
using Microsoft.UI.Xaml;
using Microsoft.UI.Xaml.Controls;

namespace Key2Joy.App.UserControls.Actions.Logic;

[MappingControl(
    ForType = typeof(SequenceAction),
    ImageResourceName = "ms-appx:///Assets/Icons/text_list_numbers.png"
)]
[ObservableObject]
public sealed partial class SequenceActionControl : UserControl, IActionOptionsControl
{
    public event EventHandler? OptionsChanged;
    public ObservableCollection<AbstractAction> ChildActions { get; } = [];

    [ObservableProperty]
    public partial AbstractAction? SelectedChildAction { get; set; }

    [ObservableProperty]
    public partial bool CanAdd { get; set; }

    public SequenceActionControl()
    {
        this.InitializeComponent();
        this.Loaded += this.OnLoaded;
    }

    private void OnLoaded(object sender, RoutedEventArgs e)
    {
        // embeddedActionControl is the x:Name field generated by XAML compiler
        this.embeddedActionControl.IsTopLevel = false;
        this.embeddedActionControl.ActionChanged += this.OnEmbeddedActionChanged;
    }

    private void OnEmbeddedActionChanged(object? sender, ActionChangedEventArgs e)
    {
        this.CanAdd = e.Action != null;
    }

    private void AddButton_Click(object sender, RoutedEventArgs e)
    {
        if (this.embeddedActionControl.Action == null)
        {
            return;
        }

        var sourceAction = this.embeddedActionControl.Action;
        var clonedAction = (AbstractAction)Activator.CreateInstance(
            sourceAction.GetType(),
            sourceAction.Name)!;
        this.embeddedActionControl.Options?.Setup(clonedAction);
        this.ChildActions.Add(clonedAction);
        OptionsChanged?.Invoke(this, EventArgs.Empty);
    }

    private void RemoveButton_Click(object sender, RoutedEventArgs e)
    {
        if (this.SelectedChildAction != null)
        {
            this.ChildActions.Remove(this.SelectedChildAction);
            OptionsChanged?.Invoke(this, EventArgs.Empty);
        }
    }

    void IActionOptionsControl.Select(AbstractAction action)
    {
        var thisAction = (SequenceAction)action;
        this.ChildActions.Clear();
        foreach (var childAction in thisAction.ChildActions)
        {
            this.ChildActions.Add(childAction);
        }
    }

    void IActionOptionsControl.Setup(AbstractAction action)
    {
        var thisAction = (SequenceAction)action;
        thisAction.ChildActions.Clear();
        foreach (var childAction in this.ChildActions)
        {
            thisAction.ChildActions.Add(childAction);
        }
    }

    bool IActionOptionsControl.CanMappingSave(AbstractAction action) => true;
}
